# Database Connection URL (pointing to our Docker container's port and DB name)
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_db

# The credentials we defined in the docker-compose.yml
spring.datasource.username=resume_user
spring.datasource.password=resume_password

# Tells Hibernate to automatically create our tables based on our @Entity classes
spring.jpa.hibernate.ddl-auto=create-drop
# Show the SQL queries in the terminal so you can see what Spring is doing behind the scenes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
